Fix Profile to User migration
The initial migration wasn't run in production, because of failing tests
(fixed in f053eee).

After fixing it, it needed to be split into data+schema migrations, to
work around:

> django.db.utils.OperationalError: cannot ALTER TABLE
> "socialee_profile" because it has pending trigger events

At least that's what happened with the (new) test for it.